apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  annotations:
    backstage.io/linguist: 'https://github.com/asdasdasd'
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: asdasdasd



